---
blank_issues_enabled: false
contact_links:
  - name: Exam AZ-104 - Microsoft Azure Administrator Crash Course Community Support
    url: https://github.com/timothywarner/az104/discussions
    about: Please ask and answer questions here.
